LABS-EU3/lambdaDoor_frontend

.github/pull_request_template.md
commit_template.md

-  Add Commit , Pull request template and branch naming conventions
- https://trello.com/c/A4TJFBj1

docs(template): create commits and pull request conventions

---

.eslintrc.json
.prettierrc
package-lock.json
package.json

- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have performed a self-review of my own code
- [x ] My code follows the style guidelines of this project
- [XX ] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
https://trello.com/c/veAY1Hrz/29-implement-code-style-guide

Initialized Eslint as well as Prettier

---

.circleci/config.yml
README.md
src/App.test.js

Setup CIrcleCI config. Also added CI status badge on the readme.
https://trello.com/c/JVRT5mGc

CircleCI Setup 

---

package-lock.json
package.json

Installed testing-library/react and ran `npm run test` to ensure Jest was installed and working.
https://trello.com/c/iXDlgDV6

chore(setup): set up test suite - installed @testing-library/react

---

.gitignore
package-lock.json
package.json
src/pages/Home.jsx

Setup sign in with slack, which retrieves the user's details from slack.
https://trello.com/c/T6zrLm4I

Setup sign in with Slack

---

package.json

fix(CI): final fix for coverage

---

src/components/Avatar.jsx
src/components/Layout/DashboardLayout.jsx
src/components/ReviewCard.jsx
src/components/ReviewList.jsx
src/components/Search.jsx
src/components/SideNav.jsx
src/pages/UserDashboard.jsx
src/state/actions/auth.js
src/state/actions/index.js
src/state/actions/user.js
src/utils/axios.js

Added environment variable for backend url
https://trello.com/c/vkSyJT21

chore(app): add env variable for backend url

---

public/index.html
src/components/Layout/DashboardLayout.jsx
src/components/ReviewList.jsx
src/components/Search.jsx
src/components/SideNav.jsx
src/pages/UserDashboard.jsx
src/state/actions/auth.js

Fixed Logout and Added Location to Profile . Also fixed bug with location request
https://trello.com/c/M2APoc9J

Fixed Logout and Added Location to Profile

---

src/pages/UserDashboard/UserDashboard.jsx
src/utils/getLocation.js

Fix Bug With Uppercase Actions

Fix Bug With Uppercase Actions

---

package-lock.json
package.json
public/index.html
src/components/LocationSearch.jsx

Moved Script from index.html to Custom Loader

Moved Script from index.html to Custom Loader

---

package-lock.json
src/components/JobTitleVisualization.jsx

fix(visualization): fix reload of visualization

---

src/components/CompanyCard/CompanyCard.jsx
src/state/actions/closestCompanies.js

Bug: fixed bug with user's credential

---

src/components/UserLocationComp/ClosestLocationList.jsx
src/pages/UserDashboard/UserDashboard.jsx
src/state/actions/closestCompanies.js

fixed-lagging-recommendations

---

src/components/CompanyReview/CompanyReviewCard.jsx
src/components/CompanyReviews/InterviewReviews/InterviewReviewList.jsx
src/components/CompanyReviews/SalaryReviews/SalaryReviewsList.jsx
src/components/MyReviews/InterviewReviews/SmallReviewCard.jsx
src/pages/Home/__test__/__snapshots__/Home.test.jsx.snap

Highlight small review card on hover to indicate to the user that they are clickable.
https://trello.com/c/w2sk3lnb

Highlight Small Review Card on Hover

---

src/components/TopRated/TopRatedList.jsx
src/components/UserLocationComp/ClosestLocationCard.jsx
src/components/UserLocationComp/ClosestLocationList.jsx

Styling fix for cards visible on dashboard (top rated cards and closest recommended cards). Currently using overflow:hidden as it looks quite clean, but can change to max-length if preferred.

Styling fix

---

src/components/Router/index.jsx
src/pages/AddReview.jsx
src/pages/UserDashboard/UserDashboard.jsx

Bug Fixes for Routes and Text Headings
https://trello.com/c/lbq7x4iS

Bug Fixes for Routes and Text Headings

---

src/components/Company/CompanyReview/CompanyReviewCard.jsx
src/components/Company/InterviewReviews/InterviewReviewList.jsx
src/components/Company/SalaryReviews/SalaryReviewsList.jsx

Edit in Company Review folder for Typo and Display

---

README.md
package-lock.json

Created Giphy videos for Documentation

---

src/components/AppInfoContainer.jsx
src/components/Layout/FooterNav/FooterNav.jsx
src/pages/Home/Home.jsx
src/styles/theme.styles.js

Styling added for different views (mobile, tablet, large tablet, small laptop)

Responsive styling

---

src/components/Company/CompanyDetails/CompanyCard.jsx
src/components/Company/InterviewReviews/InterviewReviewList.jsx
src/components/CompanySummaryCard.jsx
src/components/UserDashboard/TopRated/TopRatedList.jsx
src/components/UserDashboard/UserLocationComp/ClosestLocationList.jsx

Styling Fixes

---

src/pages/MyReviews/ManageReviews.jsx
src/state/actions/reviews.js
src/styles/theme.styles.js

Responsiveness on Mobile Landscape and Bug with Redirects on Adding Reviews
https://trello.com/c/nu6qSUbO

More Bug Fixes

---

src/components/AppInfoContainer.jsx
src/components/Layout/FooterNav/FooterNav.jsx
src/components/Layout/SideNav/SideNav.jsx
src/pages/Home/Home.jsx

Unknown location text, tooltip and notification, plus styling for landscape on the landing page and info section. (Dashboard change for unknown location still to come)

Unknown location & Styling

---

public/index.html

Changed Site Description to Custom Text

Changed Site Description to Custom Text
